### ISSUE TITLE
Erreur fatale sur page magasin

### ISSUE THREAD

**Issue by chrey** [Smile-SA/magento2-module-store-locator#10]
Lors de l'accès à une page Magasin en front, j'ai une erreur fatale

URL : /stores/nom-du-magasin

Fatal error: Call to a member function getValue() on null in /var/www/spb-magento/releases/master-201703170940/vendor/smile/module-store-locator/Helper/Contact.php on line 51

**Comment by romainruaud** [comment]
Hello,

this should have been fixed on latest release.

feel free to reopen if needed.
