### ISSUE TITLE
Static deploy on production environnement KO

### ISSUE THREAD

**Issue by zkliouel** [Smile-SA/magento2-module-store-locator#12]
Hi,

Version 1.2.0-alpha5

When i run the command line   `bin/magento setup:static-content:deploy`

I have the error below :
```
Compilation from source: /var/www/magento2/vendor/magento/theme-adminhtml-backend/web/css/styles.less

Compilation from source: 
adminhtml/Magento/backend/en_US/css/styles.less
Warning: file_get_contents(elessar/elessar.css): failed to open stream: No such file or directory in /var/www/magento2/vendor/oyejorge/less.php/lib/Less/Tree/Import.php on line 176
```
Regards

**Comment by romainruaud** [comment]
Hello,

I think you are in production mode ?

Could you give a try to https://github.com/Smile-SA/magento2-module-retailer/pull/6/files which was initially fixed on the "retailer" module but which we did not move to the storelocator module during our refactoring.

If this give you good results I will fix it by using it.

Regards,

**Comment by zkliouel** [comment]
Hello,

yes i'm on production mode and your solution seems to work.

Regards,
