### ISSUE TITLE
Opening hours does not reflect properly after save

### ISSUE THREAD

**Issue by Kailashlambe** [Smile-SA/magento2-module-store-locator#124]
**Preconditions**
Magento 2.3

         "smile/module-map": "^2.0",
        "smile/module-retailer": "1.2.9.1",
        "smile/module-seller": "^1.2",
        "smile/module-store-delivery": "^1.1",
        "smile/module-store-locator": "^2.0",

**Magento Version** : EE Cloud ver. 2.3.5-p1

**Module Store Locator Version :**
         "smile/module-map": "^2.0",
        "smile/module-retailer": "1.2.9.1",
        "smile/module-seller": "^1.2",
        "smile/module-store-delivery": "^1.1",
        "smile/module-store-locator": "^2.0",

**Environment** : Developer

**Third party modules** : no

### Steps to reproduce
1. Add/Edit any retailer information
2. change the opening hours time and save

### Expected result
1. Selected opening hours should show/display

### Actual result
1. wrong hours are shown.
 
<img width="894" alt="hours issue" src="https://user-images.githubusercontent.com/10921176/107327310-f3bf2980-6ad2-11eb-8728-bc608e22ab3a.png">

**Comment by fnogatz** [comment]
This looks familiar to me. However, in #91, the problem was suddenly gone, so I could not reproduce again.

**Comment by Kailashlambe** [comment]
Thanks @fnogatz, I am working on it, will keep you posted.

**Comment by Kailashlambe** [comment]
Hi @fnogatz, I am not sure how but  I was able to reproduce the issue on my local environment earlier and suddenly it's gone now.

But still, I am able to reproduce in my other environments(except local), any idea on this? how did you get rid of this issue in other environments?

**Comment by fnogatz** [comment]
Yeah, I had the exact same impression – suddenly, the problem was gone. I'm not sure what the reason was, sorry :(
