### ISSUE TITLE
store delivery doesn't work

### ISSUE THREAD

**Issue by gabs77** [Smile-SA/magento2-module-store-locator#20]
We can't edit the region on the admin form.
We have an error on checkout about region_id missing.
We can't place order with success

**Comment by delyriand** [comment]
Hi @gabs77,

Thank you for this issue.
Can you give more detail to reproduce the different problem?
If possible, please follow the template below.

---



### Preconditions



Magento Version :


Retailer module Version :


Environment :


Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by pavelshulga** [comment]
### Preconditions
Magento Version: 2.2.5

Retailer module Version: 1.2.1

Environment: CentOS

Third party modules: -

### Steps to reproduce
1. Make sure store country is added to "State is required" option list (Stores -> Configuration -> General -> General -> State Options)
2. Go to frontend and complete regular checkout journey (any product type) using store pickup

### Expected result
Successfully placed order, transactions emails sent to client, store owner etc

### Actual result
"regionId is a required field" error message shown after "Place order" button is clicked (please refer screenshot attached below).

### Attachments
![image](https://user-images.githubusercontent.com/31196887/44968380-f1b02280-af8a-11e8-9b41-5920f2e4db10.png)

**Comment by gcampedelli** [comment]
Hello, I'm following this topic. As matter of fact, I edited DB to add a RegionID value to the column region_id inside the table smile_retailer_address. In my case, proper value was 530. Then I tried to checkout and it worked.
