### ISSUE TITLE
Opening Hours

### ISSUE THREAD

**Issue by zkliouel** [Smile-SA/magento2-module-store-locator#3]
On a store page 

The store is indicated as closed but it should be "Opened" (it was 15h45 when i made my tests)
![opening_hours](https://cloud.githubusercontent.com/assets/1635913/22696400/21ca2304-ed4e-11e6-968b-e8b3938f6df0.png)

Also, it don't show the others opening hours of the week
![opening_hours_week](https://cloud.githubusercontent.com/assets/1635913/22696491/75db42a2-ed4e-11e6-83f6-1d71f6266fe2.png)

Thanks

**Comment by romainruaud** [comment]
You can see the other opening hours by clicking on the "Open/Closed" label on the shop page.

I will reproduce your test case and see what it renders on my environment.

Regards,
