### ISSUE TITLE
Opening Hours and Special Opening Hours are not displayed

### ISSUE THREAD

**Issue by houdaElr** [Smile-SA/magento2-module-store-locator#30]
Magento Version : 2.2.5
Module Store Locator Version : 1.3.4
Environment : LXC and Integration

### Expected result
Show the opening hours of the selected store.

### Actual result
1. 
![image](https://user-images.githubusercontent.com/30406381/47229858-0cb6e480-d3c9-11e8-9da1-a6165628bea7.png)
2.
![image](https://user-images.githubusercontent.com/30406381/47229911-340db180-d3c9-11e8-9ad3-1ac3e5102113.png)

**Comment by Fdec** [comment]
houdaElr 

Thanks for your feedback. 

It's fixed, PR is waiting for validation.

**Comment by Fdec** [comment]
PR is validated and the tag is create
