### ISSUE TITLE
Map does not load in IE

### ISSUE THREAD

**Issue by dzungnt** [Smile-SA/magento2-module-store-locator#32]
Map does not load in IE with error message Unable to get property 'name' of undefined or null reference.
### Preconditions

Magento Version : CE 2.2

Module Store Locator Version :1.2.2

Environment :

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by nelero** [comment]
seems like the issue is the same for me : 
https://github.com/Smile-SA/magento2-module-store-delivery/issues/12

**Comment by dzungnt** [comment]
It's the issue with close button, the map is works after I hidden close button.

**Comment by nelero** [comment]
thanks for the feedback.
Which one ? The close cross for the modal, or the close cross for a store delivery point ?
thanks

**Comment by nelero** [comment]
@dzungnt : any update for the fix ? thanks for your help
