### ISSUE TITLE
Mobile modal window store locator problem

### ISSUE THREAD

**Issue by pkisdar** [Smile-SA/magento2-module-store-locator#36]
Hi there,
I have a problem with the mobile view of store locator. When I choose store pickup, it opens the store-locator in a modal window. Now, I'm unable to scroll down and tap the "select store" button.

### Preconditions

Trying to choose a store for pickup from the checkout/shipping step.

Magento Version : 2.2.6 CE

Module Store Locator Version : 1.2.2

Environment : Developer mode

Third party modules : -

### Steps to reproduce

1. Use an iPhone
2. Select store pickup from the checkout/shipping page
3. Try to set the chosen store

### Expected result

1. I should be able to scroll down and tap the corresponding button.

### Actual result

1. I can select the store from the list or from the map, but can't tap the button, because I can't scroll down to it.
![img_e1249](https://user-images.githubusercontent.com/45464488/50041315-38fe8280-0053-11e9-8913-160d55cfd803.JPG)

**Comment by Fdec** [comment]
Hi @pkisdar 
Have you always the problem ?

Thanks

**Comment by Fdec** [comment]
No news, so I close this issue.
