### ISSUE TITLE
Country::getAllOptions() must be compatible

### ISSUE THREAD

**Issue by evshv** [Smile-SA/magento2-module-store-locator#41]
https://github.com/Smile-SA/magento2-module-store-locator/blob/72f186fa260800b6e0c8b9df50ab89a1b2fa3e31/Model/RetailerAddress/Source/Country.php#L57

Magento 2.3
`php bin/magento setup:di:compile`

Fatal error: Declaration of Smile\StoreLocator\Model\RetailerAddress\Source\Country::getAllOptions() must be compatible with Magento\Eav\Model\Entity\Attribute\Source\Table::getAllOptions($withEmpty = true, $defaultValues = false) in /var/www/cofel/vendor/smile/module-store-locator/Model/RetailerAddress/Source/Country.php on line 67

**Comment by Ahmed-Ayman** [comment]
fixed this by changing the mntioned line to -> public function getAllOptions($withEmpty = true, $defaultValues = false)

**Comment by pusachev** [comment]
@all Also
Please process previous PR's
https://github.com/Smile-SA/magento2-module-store-locator/pull/38
https://github.com/Smile-SA/magento2-module-store-locator/pull/42

**Comment by romainruaud** [comment]
Fixed in master branch. Will release a minor version.
