### ISSUE TITLE
On BO > Sellers Grid : "undefined index extension_attributes"

### ISSUE THREAD

**Issue by livca-smile** [Smile-SA/magento2-module-store-locator#45]
On Magento 2.3 Backoffice > Sellers grid, got a php error "undefined index extension_attributes" on Plugin/RetailerCollectionPlugin.php line 104

### Preconditions

on a LXC server
centos7
php 7.2.10
elasticsearch 6.6.1
analysis-icu      6.6.1
analysis-phonetic 6.6.1

Magento Version : CE 2.3.0

Module Store Locator Version : 
smile/module-storelocator : 1.3.6
smile/module-map : 1.1.5

Environment : developer mode

Third party modules :

    "require": {
        "magento/product-community-edition": "2.3.0",
        "mageplaza/magento-2-arabic-language-pack": "dev-master",
        "mageplaza/magento-2-french-language-pack": "dev-master",
        "smile/elasticsuite": "^2.7",
        "smile/magento2-library-framework": "^4.0",
        "smile/module-backend": "^4.0",
        "smile/module-core": "^4.0",
        "smile/module-cron": "^4.0",
        "smile/module-indexer": "^4.0",
        "smile/module-map": "^1.1",
        "smile/module-patch": "^1.0",
        "smile/module-reconfigure": "^4.0",
        "smile/module-retailer": "^1.2",
        "smile/module-seller": "^1.2",
        "smile/module-store-locator": "^1.3",
        "smile/module-varnish": "^4.0"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "~2.13.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento2-functional-testing-framework": "2.3.9",
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "smile/magento2-library-testframework": "^4.0",
        "smile/module-debug-toolbar": "^4.0",
        "smile/php-codesniffer-rules-magento-2": "^2.0",
        "smile/spbuilder": "^4.0",
        "squizlabs/php_codesniffer": "3.3.1"
    },

### Steps to reproduce

1. On Magento 2.3 Backoffice
2. Go to Sellers grid
3. Got a php error 

### Expected result

1. Grid should be loaded

### Actual result

1. "undefined index extension_attributes" on line 104
2. line 104 is if ($data[ExtensibleDataInterface::EXTENSION_ATTRIBUTES_KEY]), should be if (isset($data[ExtensibleDataInterface::EXTENSION_ATTRIBUTES_KEY]))

**Comment by Fdec** [comment]
Thanks for the report @livca-smile
