### ISSUE TITLE
Google Map in Store locator for Magento 2 does not work in IE 11

### ISSUE THREAD

**Issue by ozzman6154** [Smile-SA/magento2-module-store-locator#47]
Map does not display in IE 11.

### Preconditions
Magento Commerce Cloud 2.3.0
Smile Store locator module version - 1.3.7
Map module - 1.1.5
Environment : Production mode
Third party modules : N/A.  Issue can be reproduced on Magento 2 base Luma theme

### Steps to reproduce
1. Install the modules on base luma theme and enable the extension
2. Open IE 11 browser and add product to cart and navigate to Checkout on Shipping page
3. Select store pickup and view the map

### Expected result
1. Map should be displayed

### Actual result
1. Map is not displayed.  

Frontend and browser console screenshot:  

![image](https://user-images.githubusercontent.com/18482653/55927549-cbf1a700-5c58-11e9-804d-e117854be720.png)

**Comment by romainruaud** [comment]
Hello @ozzman6154 

I'm afraid that supporting such an old/outdated browser is out of the scope of our Open Source support commitment on Github.

We'd be happy to merge any PR if you are able to fix it, or to provide you dedicated (commercial) support to fix this issue.

Regards
