### ISSUE TITLE
Ghost dependency with Smile_RetailerOffer

### ISSUE THREAD

**Issue by ubermanu** [Smile-SA/magento2-module-store-locator#53]
Creating a new retailer in admin throws an exception if Smile_RetailerOffer is not installed.

### Preconditions

Magento Version : 2.2.8 CE
Module Store Locator Version : 1.3.9.2
Environment : Developer

### Steps to reproduce
1. Go to Magento 2 Admin
2. Sellers >  Retailers
3. Add New Retailer

### Expected result
Access the retailer creation form.

### Actual result

> Exception #0 (ReflectionException): Class Smile\RetailerOffer\Ui\Component\Offer\Form\Retailer\Options does not exist

https://pastebin.com/NvVb6jcC

**Comment by ubermanu** [comment]
see #48

**Comment by Fdec** [comment]
@ubermanu thanks for the report. I fix it this day. stay tuned.

**Comment by Fdec** [comment]
Fixed, I should release it soon. 
Be careful, this fix include also an update of Retailer module.
