### ISSUE TITLE
OpenStreet map copyright is missing

### ISSUE THREAD

**Issue by ahuri909** [Smile-SA/magento2-module-store-locator#61]
When store locator is configured to use OpenStreetMap, there is no credit to OpenStreetMap.
It's clearly stated in OpenStreet map copyright that OpenStreetMap contributors should be credited 👍 

> You are free to copy, distribute, transmit and adapt our data, as long as you credit OpenStreetMap and its contributors.
> We require that you use the credit “© OpenStreetMap contributors”. [...] You may do this by linking to this copyright page.
Source : : https://www.openstreetmap.org/copyright

### Preconditions

Configure Store Locator to use OpenStreetMap

Magento verisn : Any

Module Store Locator Version : any

Environment : any

### Expected result

When browsing map, the credit should appear in the right-bottom corner of the map.
- Text : “© OpenStreetMap contributors”
- Link on "OpenStreetMap" to : https://www.openstreetmap.org/copyright

**Comment by IgorSIT** [comment]
Hi, 
Issue was fixed into PR #62
