### ISSUE TITLE
During save or delete of retailer, Magento requests FULL cache flush to Varnish. 

### ISSUE THREAD

**Issue by IgorSIT** [Smile-SA/magento2-module-store-locator#69]
### Preconditions

Magento Version : 2.2.9 (Commerce)

Module Store Locator Version : 1.3.9.4

Environment : Production mode

### Steps to reproduce

1. Login to Backend.
2. Go to Sellers -> Retailers.
3. Select any Retailer and go to Retailer page.
4. Click "Save" button (even without changes of retailer).

### Expected result

During save or delete of retailer, Magento must request cache flush to Varnish only for needed tags (for example "smile_seller", "smile_store_locator_markers") not FULL cache flush to Varnish.

### Actual result

During save or delete of retailer, Magento requests FULL cache flush to Varnish. 
Screens from log:

`##.###.###.### - - [24/Oct/2019:15:29:58  0200] "POST /admin/smile_retailer/retailer/save/key/###############/ HTTP/1.1" 302 1014 "https://www.#####.###/admin/smile_retailer/retailer/edit/id/258/key/###############/" ...`

`##.###.###.### [24/Oct/2019:15:29:59  0200] "PURGE http://www.#####.###/ HTTP/1.1" 200  X-Magento-Tags-Pattern:.*`

The " .* " means "everything" or "full".

Each time a POST to /admin/smile_retailer/retailer/save/key/../ is done, a fulll Varnish cache flush is executed.

The "smile/module-retailer" module is related with "smile/module-store-locator" module. And "smile/module-store-locator" module use observer for events "smile_seller_save_after" and "smile_seller_delete_after". These observers clean store locator marker cache when we save or delete of seller (retailer). During execute these events (actions) are trigger other "adminhtml_cache_refresh_type" event which request FULL cache flush to Varnish.
Part of code:

`$this->purgeCache->sendPurgeRequest('.*');`

**Comment by IgorSIT** [comment]
To fix it, I changed code of observer for events "smile_seller_save_after" and "smile_seller_delete_after". 
So, during save or delete of Retailer, Magento requests cache flush to Varnish only for needed tag "smile_store_locator_markers" not FULL cache flush to Varnish:

[https://github.com/Smile-SA/magento2-module-store-locator/pull/70/commits/fe599d34c4944ee7892c89ffbcc9aa8bb903f57b](url)

**Comment by Fdec** [comment]
https://github.com/Smile-SA/magento2-module-store-locator/pull/70
