### ISSUE TITLE
Special opening hours are not available in BE

### ISSUE THREAD

**Issue by skylineop** [Smile-SA/magento2-module-store-locator#87]
### Preconditions
Magento Version: 2.3.3 (Commerce)
Store Locator Module Version: 2.0.0

### Steps to reproduce
1. Go to Admin -> Sellers -> Retailers.
2. Click "Add New Retailer" button.
3. Special opening hours group.
4. Add special Opening Hours
5. Check form.

### Expected result
Special opening hours are available to manage.

### Actual result
Special opening hours are not available to manage.
<img width="1334" alt="Screen Shot 2020-01-06 at 1 00 17 pm" src="https://user-images.githubusercontent.com/12101827/72158304-9124c700-33c2-11ea-94a4-ce0c3b9e6373.png">

**Comment by james-lockhart** [comment]
Hey @Fdec  
Just wondering do you have an ETA as to when this issue will be resolved? 
As it we are experiencing the same issue and is holding us up from finishing set up.

**Comment by rakibabu** [comment]
Fixed in PR: https://github.com/Smile-SA/magento2-module-store-locator/pull/88

**Comment by Fdec** [comment]
Hi @rakibabu 

Thanks for the PR
