### ISSUE TITLE
Can't pass through the checkout steps when current store is not set by customer

### ISSUE THREAD

**Issue by zkliouel** [Smile-SA/magento2-module-store-locator#9]
On checkout/cart page

When the ajax call bellow is done 
{{URL}}/customer/section/load/?sections=compare-products%2Ccustomer%2Ccurrent-store%2Cmessages%2Cwishlist&update_section_id=false&_=148959568112

I have the error bellow : 
` {"message":"Warning: array_key_exists() expects parameter 2 to be array, null given in /vendor/magento/module-customer/CustomerData/Section/Identifier.php on line 82"}`

I Think it's due to the di : vendor/smile/module-store-locator/etc/frontend/di.xml

For now i just quick local  fixed that changing the file Magento\Customer\CustomerData\Section\Identifier.php on method markSections adding the condition : isset($sectionsData[$name]) 

Hope it will help you

Regards

**Comment by romainruaud** [comment]
Fixed by https://github.com/Smile-SA/magento2-module-store-locator/commit/53c972873b208ab72ecebf81336b98c962f8fa62
