### ISSUE TITLE
getValues() of time slots are incorrect

### ISSUE THREAD

**Issue by fnogatz** [Smile-SA/magento2-module-store-locator#91]
### Preconditions

Magento Version : v2.3.4 CE
Module Store Locator Version : v1.3.9.5; but the related code is not touched since then in the current `master` branch
Environment : Developer
Third party modules : Some, yes ;)

### Steps to reproduce
1. Create a retailer, add *Opening Hours* for *Monday* as "10:00 - 13:00":
    ![Screenshot from 2020-03-11 01-15-07](https://user-images.githubusercontent.com/881988/76370005-cd7a9200-6335-11ea-9f8e-0e54af290c7c.png)
1.  Click on *Save and Continue Edit*
1.  Go to *Opening Hours* again

### Expected result
The time as set before should be shown for *Monday*.

### Actual result
Instead, the time is shown as something different:
![Screenshot from 2020-03-11 01-18-14](https://user-images.githubusercontent.com/881988/76370174-47128000-6336-11ea-8fc8-17812417fbbf.png)

### Possible solution

I tracked this down to be a problem with the method `getValues()` in `Block/Adminhtml/Retailer/OpeningHours/Element/Renderer.php`. The JavaScript rangebar used to show the ranges expects dates of the `DateTime::DATETIME_INTERNAL_FORMAT` format (`yyyy-MM-dd HH:mm:ss`) with the current date set. The current implementation of `getValues()` however incorrectly uses `Zend_Date`'s `setTime()` method, resulting in a different date (though the time -- which is actually significant for our use-case here -- is still correct). For today, a start date of `2020-11-03 10:00:00` is returned instead of the correct `2020-03-11 10:00:00`.

`Zend_Date`'s `setTime()` method does not really take into account the provided `'h:mm a'` format. I managed to fix this by replacing the module's `getValues` method with the following:

```php
    private function getValues()
    {
        $values = [];
        if ($this->element->getValue()) {
            foreach ($this->element->getValue() as $timeSlot) {
                $date   = $this->date->date()->format('Y-m-d');
                $startTime = $date . ' ' . $timeSlot->getStartTime() . ':00';
                $endTime   = $date . ' ' . $timeSlot->getEndTime() . ':00';
                $values[]  = [$startTime, $endTime];
            }
        }

        return $values;
    }
```

I'm sure there are more elegant ways to solve this :laughing: Let me know if I should open a PR or you fix it in another way.

**Comment by Fdec** [comment]
Hi @fnogatz 

I'm in 2.3.4 CE and I don't reproduce.

**Comment by fnogatz** [comment]
Uhm, I am embarrassed I now can't reproduce either :man_facepalming: I was thinking of this being a problem with the browser localisation settings, but as I have not changed anything since then...

Sorry for the confusion, it's working now, so closing here.
