### ISSUE TITLE
v2 introduces dependency on Smile_Elasticsuite*

### ISSUE THREAD

**Issue by fnogatz** [Smile-SA/magento2-module-store-locator#93]
As of version 1.x, it was possible to use this module stand-alone. With v2, the autocomplete feature introduces a dependency on some `Smile_Elasticsuite*` components, as in, e.g., [class `Smile\StoreLocator\Model\Autocomplete\Data`](https://github.com/Smile-SA/magento2-module-store-locator/blob/afadbb8dbf8a87e5900bd86abeba2dd8bc67d134/Model/Autocomplete/DataProvider.php#L18-L19), which uses `Smile\ElasticsuiteCore\Helper\Autocomplete` and `Smile\ElasticsuiteRetailer\Model\ResourceModel\Fulltext\CollectionFactory`. This dependency is not reflected in `composer.json`.

Any chance to keep the separation as in v1.x? We would like to keep using `Smile_StoreLocator` with the ability to upgrade to v2 at some point :)

**Comment by Fdec** [comment]
Hi @fnogatz 

Indeed, I will try to find a solution.

stay tuned.

**Comment by romainruaud** [comment]
As discussed, everything related to search and/or autocompletion should be put in this module instead of here : https://github.com/Smile-SA/magento2-module-retailer-elasticsuite-search

@Fdec can you also put somewhere in the documentation that this module exists ? :)

Regards

**Comment by Fdec** [comment]
Hi @fnogatz 

It's fixed. You can update to 2.0.2 release. 
Thanks for the report !

Fanny
